name: flutter_body_atlas
description: |
  An interactive, SVG-based human body atlas for Flutter. 
  High-fidelity anatomical diagrams with built-in support for hit testing, highlighting, and custom integration
version: 0.1.1
repository: "https://github.com/kit-g/flutter-body-atlas"
issue_tracker: "https://github.com/kit-g/flutter-body-atlas/issues"
homepage: "https://kit-g.github.io/flutter-body-atlas/"

environment:
  sdk: ^3.10.8
  flutter: ">=3.38.0"

dependencies:
  flutter: { sdk: flutter }
  flutter_svg: ^2.2.3
  path_drawing: ^1.0.1
  xml: ^6.6.1

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/svg/

topics:
  - flutter
  - anatomy
  - fitness
  - health
  - education